### ISSUE TITLE
platformframeworksbaseが存在しない

### ISSUE THREAD

**Issue by hiroto7** [kuri8ive/APSEC2019Class#3]
READMEの手順6で， `APSEC2019Class/data/raw_data/platformframeworksbase` が存在せずエラーとなってしまう．
```
-----

evaldata
25764 Java files found.
Exception in thread "main" java.lang.IllegalStateException: SrcDir does not exist or is not a directory: /APSEC2019Class/data/raw_data/platformframeworksbase
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:82)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:89)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:65)
        at Main.main(Main.java:84)
```

**Comment by kuri8ive** [comment]
Thank you for opening this issue.
I'll address it.
